services:
  db:
    image: postgres:latest
    container_name: claimcheck-db
    environment:
      POSTGRES_DB: claimcheck
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - claimcheck-db-data:/var/lib/postgresql

volumes:
  claimcheck-db-data:
