// <auto-generated />
using System;
using ClaimCheck.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClaimCheck.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClaimCheck.Domain.Claims.ClaimAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClaimText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClaimAnalyses");
                });

            modelBuilder.Entity("ClaimCheck.Domain.Claims.ClaimAnalysis", b =>
                {
                    b.OwnsOne("ClaimCheck.Domain.Claims.ClaimAnalysisResult", "Result", b1 =>
                        {
                            b1.Property<Guid>("ClaimAnalysisId");

                            b1.PrimitiveCollection<string>("CounterArguments")
                                .IsRequired();

                            b1.Property<string>("Explanation")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("Techniques")
                                .IsRequired();

                            b1.Property<int>("TruthfulnessScore");

                            b1.HasKey("ClaimAnalysisId");

                            b1.ToTable("ClaimAnalyses");

                            b1
                                .ToJson("Result")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ClaimAnalysisId");
                        });

                    b.Navigation("Result")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
